// Toolbox definition matching bot.deriv.com's block categories.
// Six top-level categories with nested subcategories under Analysis and Utility.
// Blockly toolbox JSON format — converted to XML at runtime by Blockly.

import type { ToolboxInfo } from 'blockly/core/utils/toolbox'

export const toolbox: ToolboxInfo = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category',
      name: 'Trade parameters',
      categorystyle: 'trade_parameters',
      contents: [
        { kind: 'block', type: 'trade_definition' },
      ],
    },
    {
      kind: 'category',
      name: 'Purchase conditions',
      categorystyle: 'purchase_conditions',
      contents: [
        { kind: 'block', type: 'before_purchase' },
        { kind: 'block', type: 'purchase' },
        { kind: 'block', type: 'ask_price' },
        { kind: 'block', type: 'payout' },
      ],
    },
    {
      kind: 'category',
      name: 'Sell conditions',
      categorystyle: 'sell_conditions',
      contents: [
        { kind: 'block', type: 'during_purchase' },
        { kind: 'block', type: 'check_sell' },
        { kind: 'block', type: 'sell_at_market' },
        { kind: 'block', type: 'sell_price' },
      ],
    },
    {
      kind: 'category',
      name: 'Restart trading conditions',
      categorystyle: 'trade_results',
      contents: [
        { kind: 'block', type: 'after_purchase' },
        { kind: 'block', type: 'contract_check_result' },
        { kind: 'block', type: 'read_details' },
        { kind: 'block', type: 'trade_again' },
      ],
    },
    {
      kind: 'category',
      name: 'Analysis',
      categorystyle: 'analysis',
      contents: [
        {
          kind: 'category',
          name: 'Technical analysis',
          categorystyle: 'technical_analysis',
          contents: [
            { kind: 'block', type: 'tick' },
            { kind: 'block', type: 'ticks' },
            { kind: 'block', type: 'last_digit' },
            { kind: 'block', type: 'check_direction' },
            { kind: 'block', type: 'stat' },
          ],
        },
        {
          kind: 'category',
          name: 'Candles',
          categorystyle: 'candle',
          contents: [
            { kind: 'block', type: 'is_candle_black' },
            { kind: 'block', type: 'ohlc_values_in_list' },
            { kind: 'block', type: 'read_ohlc_obj' },
          ],
        },
        {
          kind: 'category',
          name: 'Indicators',
          categorystyle: 'indicators',
          contents: [
            { kind: 'block', type: 'sma_statement' },
            { kind: 'block', type: 'ema_statement' },
            { kind: 'block', type: 'rsi_statement' },
            { kind: 'block', type: 'bb_statement' },
            { kind: 'block', type: 'smaa_statement' },
            { kind: 'block', type: 'emaa_statement' },
            { kind: 'block', type: 'rsia_statement' },
            { kind: 'block', type: 'bba_statement' },
            { kind: 'block', type: 'macda_statement' },
          ],
        },
      ],
    },
    {
      kind: 'category',
      name: 'Utility',
      categorystyle: 'utility',
      contents: [
        {
          kind: 'category',
          name: 'Logic',
          categorystyle: 'logic',
          contents: [
            { kind: 'block', type: 'controls_if' },
            { kind: 'block', type: 'logic_compare' },
            { kind: 'block', type: 'logic_operation' },
            { kind: 'block', type: 'logic_negate' },
            { kind: 'block', type: 'logic_boolean' },
            { kind: 'block', type: 'logic_null' },
            { kind: 'block', type: 'logic_ternary' },
          ],
        },
        {
          kind: 'category',
          name: 'Math',
          categorystyle: 'math',
          contents: [
            { kind: 'block', type: 'math_number' },
            { kind: 'block', type: 'math_arithmetic' },
            { kind: 'block', type: 'math_single' },
            { kind: 'block', type: 'math_trig' },
            { kind: 'block', type: 'math_constant' },
            { kind: 'block', type: 'math_number_property' },
            { kind: 'block', type: 'math_round' },
            { kind: 'block', type: 'math_change' },
            { kind: 'block', type: 'math_on_list' },
            { kind: 'block', type: 'math_modulo' },
            { kind: 'block', type: 'math_constrain' },
            { kind: 'block', type: 'math_random_int' },
            { kind: 'block', type: 'math_random_float' },
          ],
        },
        {
          kind: 'category',
          name: 'Loops',
          categorystyle: 'loops',
          contents: [
            { kind: 'block', type: 'controls_repeat_ext' },
            { kind: 'block', type: 'controls_repeat' },
            { kind: 'block', type: 'controls_whileUntil' },
            { kind: 'block', type: 'controls_for' },
            { kind: 'block', type: 'controls_forEach' },
            { kind: 'block', type: 'controls_flow_statements' },
          ],
        },
        {
          kind: 'category',
          name: 'Text',
          categorystyle: 'text',
          contents: [
            { kind: 'block', type: 'text' },
            { kind: 'block', type: 'text_join' },
            { kind: 'block', type: 'text_statement' },
            { kind: 'block', type: 'text_append' },
            { kind: 'block', type: 'text_length' },
            { kind: 'block', type: 'text_isEmpty' },
            { kind: 'block', type: 'text_indexOf' },
            { kind: 'block', type: 'text_charAt' },
            { kind: 'block', type: 'text_getSubstring' },
            { kind: 'block', type: 'text_changeCase' },
            { kind: 'block', type: 'text_trim' },
            { kind: 'block', type: 'text_print' },
            { kind: 'block', type: 'text_prompt_ext' },
          ],
        },
        {
          kind: 'category',
          name: 'Lists',
          categorystyle: 'lists',
          contents: [
            { kind: 'block', type: 'lists_create_with' },
            { kind: 'block', type: 'lists_repeat' },
            { kind: 'block', type: 'lists_length' },
            { kind: 'block', type: 'lists_isEmpty' },
            { kind: 'block', type: 'lists_indexOf' },
            { kind: 'block', type: 'lists_getIndex' },
            { kind: 'block', type: 'lists_setIndex' },
            { kind: 'block', type: 'lists_getSublist' },
            { kind: 'block', type: 'lists_split' },
            { kind: 'block', type: 'lists_sort' },
          ],
        },
        {
          kind: 'category',
          name: 'Time',
          categorystyle: 'time',
          contents: [
            { kind: 'block', type: 'epoch' },
            { kind: 'block', type: 'timeout' },
            { kind: 'block', type: 'tick_delay' },
            { kind: 'block', type: 'todatetime' },
            { kind: 'block', type: 'totimestamp' },
          ],
        },
        {
          kind: 'category',
          name: 'Miscellaneous',
          categorystyle: 'miscellaneous',
          contents: [
            { kind: 'block', type: 'balance' },
            { kind: 'block', type: 'notify' },
            { kind: 'block', type: 'console' },
            { kind: 'block', type: 'total_profit' },
            { kind: 'block', type: 'total_runs' },
            { kind: 'block', type: 'block_holder' },
            { kind: 'block', type: 'set_stake' },
            { kind: 'block', type: 'get_stake' },
          ],
        },
        {
          kind: 'category',
          name: 'Variables',
          custom: 'VARIABLE',
        },
        {
          kind: 'category',
          name: 'Functions',
          custom: 'PROCEDURE',
        },
      ],
    },
  ],
}
